//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhythm.SSIS.Tasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rhythm.SSIS.Tasks.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;ALTER TABLE [dbo].[&apos;+FTName+&apos;] ADD CONSTRAINT [&apos;+FKName+&apos;] FOREIGN KEY (&apos;+FTFields+&apos;) REFERENCES [&apos;+STName+&apos;] (&apos;+STFields+&apos;) &apos;+FKType AS AlterScript, STName AS SourceTableName, FTName AS ForeignKeyTableName
        ///	FROM #Temp1.
        /// </summary>
        internal static string CreateFKScript {
            get {
                return ResourceManager.GetString("CreateFKScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	SET NOCOUNT ON;
        ///
        ///	DECLARE @FKName NVARCHAR(128)
        ///	, @FKColumnName NVARCHAR(128)
        ///	, @PKColumnName NVARCHAR(128)
        ///	, @fTableName NVARCHAR(128)
        ///	, @fUpdateRule INT
        ///	, @fDeleteRule INT
        ///	, @FieldNames NVARCHAR(500)
        ///
        ///
        ///	CREATE TABLE #Temp(
        ///		PKTABLE_QUALIFIER NVARCHAR(128),
        ///		PKTABLE_OWNER NVARCHAR(128),
        ///		PKTABLE_NAME NVARCHAR(128),
        ///		PKCOLUMN_NAME NVARCHAR(128),
        ///		FKTABLE_QUALIFIER NVARCHAR(128),
        ///		FKTABLE_OWNER NVARCHAR(128),
        ///		FKTABLE_NAME NVARCHAR(128),
        ///		FKCOLUMN_NAME NVARCHAR(128),
        ///		KEY_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DropCreateFKScriptCommon {
            get {
                return ResourceManager.GetString("DropCreateFKScriptCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;ALTER TABLE dbo.&apos;+ STName +&apos; DROP CONSTRAINT &apos;+ FKName AS DropScript, STName AS SourceTableName, FTName AS ForeignKeyTableName
        ///FROM #Temp1.
        /// </summary>
        internal static string DropFKScript {
            get {
                return ResourceManager.GetString("DropFKScript", resourceCulture);
            }
        }
    }
}
